### ISSUE TITLE
How to deal with collection instantiation

### ISSUE THREAD

**Issue by yanndebelgique** [radekmie/meteor-flow-types#3]
Hi,

how do I deal with the following?
const WidgetCollection = new Mongo.Collection('widget_collection');

const a_widget = WidgetCollection.findOne();

I have a WidgetType => How to I automatically assign WidgetType to the variable a_widget?

**Comment by radekmie** [comment]
Well, it's not so automatic (yet). Let's study an example:

```js
type NoteType = {
  _id: string;
  of:  number;
};

export const Notes: Meteor$Mongo$Collection<NoteType> = new Mongo.Collection('notes');

const x = Notes.findOne({}, {transform: x => x});
if (x)
  console.log(x._id, x.of, x.a); // Works, reports x.a.

const y = (Notes.findOne(): ?NoteType);
if (y)
  console.log(y._id, y.of, y.a); // Works, reports x.a.

const z = Notes.findOne();
if (z)
  console.log(z._id, z.of, z.a); // Nope, z has an empty type.

// Same goes with the Notes.find.
```

Currently, using `Meteor$Mongo$Collection<T>` works only if you specify the `transform` function or you'll cast it explicitly to `?T` (`findOne`) or `Meteor$Mongo$Cursor<T>` (`find`). If there'll be another way, I'll definitely let you know.

**Comment by radekmie** [comment]
OK, it turned out, that it is possible in the newer versions of flow. I'll push an update soon. After that change, marking the collection as `Meteor$Mongo$Collection<T>` will be enough.

**Comment by yanndebelgique** [comment]
Thx!

Apologies for brevity and typos. Sent from my iPhone
